apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  namespace: $NS
  labels:
    type: local
    app: vault
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ${V_VAULT_DATA_SHARE_DIR}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: $NS
  labels:
    app: vault
spec:
  volumeName: vault-pv
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi